#!/usr/bin/env bash
# setup-hooks.sh — wire Throughline's write-safety hooks for macOS/Linux (no Python required).
# Writes the gitignored .claude/settings.local.json and rebuilds .codex/hooks.json with the
# bash + .sh launchers. Equivalent to `python3 tools/setup-hooks.py` on Unix.
#
# If a JSON parser (python3) is present it is used for a clean merge that preserves any
# existing keys (e.g. target access). Without it, a fresh hooks-only file is written when
# none exists; if one already exists, you are told to add the hooks block (or install python3)
# so existing settings are never clobbered.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

PY="$(command -v python3 || command -v python || command -v py || true)"
if [ -n "$PY" ]; then
  exec "$PY" "$ROOT/tools/setup-hooks.py"
fi

claude_local="$ROOT/.claude/settings.local.json"
codex_path="$ROOT/.codex/hooks.json"

claude_hooks_json() {
cat <<'JSON'
{
  "hooks": {
    "PreToolUse": [
      { "matcher": "Write|Edit|MultiEdit|NotebookEdit",
        "hooks": [ { "type": "command", "command": "bash .claude/hooks/validate-immutable-paths.sh", "timeout": 10 } ] },
      { "matcher": "Bash",
        "hooks": [ { "type": "command", "command": "bash .claude/hooks/validate-bash-safety.sh", "timeout": 10 } ] }
    ],
    "PostToolUse": [
      { "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          { "type": "command", "command": "bash .claude/hooks/log-tool-use.sh", "timeout": 15 },
          { "type": "command", "command": "bash .claude/hooks/check-code-quality.sh", "timeout": 30 }
        ] }
    ]
  }
}
JSON
}

if [ -f "$claude_local" ] && [ -s "$claude_local" ]; then
  echo "WARN: $claude_local already exists and no JSON parser is available to merge safely."
  echo "      Add this 'hooks' block to it by hand (or install python3 and re-run):"
  claude_hooks_json
else
  claude_hooks_json > "$claude_local"
  echo "wrote $claude_local"
fi

cat > "$codex_path" <<'JSON'
{
  "_comment": "Generated by tools/setup-hooks.sh for macOS/Linux. Re-run after switching OS. Codex sends the same stdin JSON + exit-2 protocol; the shared .github guard scripts apply.",
  "hooks": {
    "PreToolUse": [
      { "matcher": "apply_patch|Edit|Write",
        "hooks": [ { "type": "command", "command": "bash .github/hooks/scripts/validate-immutable-paths.sh", "timeout": 10, "statusMessage": "Guarding /standards/ + /exemplars/ (read-only)" } ] },
      { "matcher": "Bash",
        "hooks": [ { "type": "command", "command": "bash .github/hooks/scripts/validate-bash-safety.sh", "timeout": 10, "statusMessage": "Blocking writes to immutable paths + git push/merge (human-only)" } ] }
    ],
    "PostToolUse": [
      { "matcher": "apply_patch|Edit|Write",
        "hooks": [
          { "type": "command", "command": "bash .github/hooks/scripts/log-tool-use.sh", "timeout": 15, "statusMessage": "Appending to wiki/log.md" },
          { "type": "command", "command": "bash .github/hooks/scripts/check-code-quality.sh", "timeout": 30, "statusMessage": "Quality lint on written files" }
        ] }
    ]
  }
}
JSON
echo "wrote $codex_path"
echo "Throughline hooks wired for macOS/Linux (bash + .sh)."
