#!/usr/bin/env python3
"""Wire Throughline's write-safety hooks for the host OS.

Why this exists: Claude Code and Codex hook configs take a single `command`
string with no per-OS branch, and no interpreter name is present on every OS
(Windows runs `py`/`powershell`; macOS/Linux run `python3`; `bash` is not on the
Windows PATH outside Git Bash). So the correct launcher has to be chosen per
machine. This script does that, idempotently.

What it writes:
  - .claude/settings.local.json  (gitignored)  -> merges a `hooks` block
  - .codex/hooks.json            (in place)     -> rebuilt for this OS

The cross-platform read-only guard on /standards/ and /exemplars/ lives in the
committed .claude/settings.json `permissions.deny` block and needs no setup.

This Python version is OPTIONAL. The default, no-dependency path is the shell-native
setup that needs nothing beyond the OS shell:
  Windows:      powershell -ExecutionPolicy Bypass -File tools\\setup-hooks.ps1
  macOS/Linux:  bash tools/setup-hooks.sh
Use this Python script only if you prefer it:
  Windows:      py tools\\setup-hooks.py
  macOS/Linux:  python3 tools/setup-hooks.py
"""
import json
import os
import platform
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IS_WINDOWS = platform.system() == "Windows"


def launcher(ps1_relpath, sh_relpath):
    """Return the OS-correct command string for a hook script pair."""
    if IS_WINDOWS:
        return f"powershell -NoProfile -ExecutionPolicy Bypass -File {ps1_relpath}"
    # POSIX: invoke through bash so it works whether or not the file is +x.
    return f"bash {sh_relpath}"


def claude_command(basename):
    return launcher(f".claude/hooks/{basename}.ps1", f".claude/hooks/{basename}.sh")


def codex_command(basename):
    # Codex reuses the Copilot/.github guard scripts.
    return launcher(
        f".github/hooks/scripts/{basename}.ps1",
        f".github/hooks/scripts/{basename}.sh",
    )


def block(matcher, *basenames, cmd):
    return {
        "matcher": matcher,
        "hooks": [{"type": "command", "command": cmd(b), "timeout": t} for b, t in basenames],
    }


def claude_hooks():
    return {
        "PreToolUse": [
            {
                "matcher": "Write|Edit|MultiEdit|NotebookEdit",
                "hooks": [{"type": "command", "command": claude_command("validate-immutable-paths"), "timeout": 10}],
            },
            {
                "matcher": "Bash",
                "hooks": [{"type": "command", "command": claude_command("validate-bash-safety"), "timeout": 10}],
            },
        ],
        "PostToolUse": [
            {
                "matcher": "Write|Edit|MultiEdit",
                "hooks": [
                    {"type": "command", "command": claude_command("log-tool-use"), "timeout": 15},
                    {"type": "command", "command": claude_command("check-code-quality"), "timeout": 30},
                ],
            }
        ],
    }


def codex_hooks_json():
    return {
        "_comment": (
            "Generated by tools/setup-hooks.py for this OS. Codex delivers the same stdin "
            "JSON (tool_name/tool_input/tool_response) and blocks on exit code 2, so the "
            "shared .github guard scripts apply. Re-run setup-hooks.py after switching OS. "
            "NOTE: Codex routes file edits through apply_patch (a patch diff), so "
            "validate-immutable-paths must read the patch target, not only tool_input.file_path "
            "-- verify per .codex/VERIFICATION.md."
        ),
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "apply_patch|Edit|Write",
                    "hooks": [{"type": "command", "command": codex_command("validate-immutable-paths"), "timeout": 10,
                               "statusMessage": "Guarding /standards/ + /exemplars/ (read-only)"}],
                },
                {
                    "matcher": "Bash",
                    "hooks": [{"type": "command", "command": codex_command("validate-bash-safety"), "timeout": 10,
                               "statusMessage": "Blocking writes to immutable paths + git push/merge (human-only)"}],
                },
            ],
            "PostToolUse": [
                {
                    "matcher": "apply_patch|Edit|Write",
                    "hooks": [
                        {"type": "command", "command": codex_command("log-tool-use"), "timeout": 15,
                         "statusMessage": "Appending to wiki/log.md"},
                        {"type": "command", "command": codex_command("check-code-quality"), "timeout": 30,
                         "statusMessage": "Quality lint on written files"},
                    ],
                },
            ],
        },
    }


def write_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")


def main():
    os_name = platform.system() or "unknown"

    # 1. Claude Code: merge hooks into the gitignored machine-local settings.
    claude_local = os.path.join(ROOT, ".claude", "settings.local.json")
    settings = {}
    if os.path.exists(claude_local):
        try:
            with open(claude_local, encoding="utf-8") as f:
                settings = json.load(f)
        except (ValueError, OSError):
            settings = {}
    settings["hooks"] = claude_hooks()
    write_json(claude_local, settings)

    # 2. Codex: rebuild hooks.json in place for this OS.
    codex_path = os.path.join(ROOT, ".codex", "hooks.json")
    if os.path.isdir(os.path.dirname(codex_path)):
        write_json(codex_path, codex_hooks_json())

    launcher_kind = "powershell + .ps1" if IS_WINDOWS else "bash + .sh"
    print(f"Throughline hooks wired for {os_name} ({launcher_kind}).")
    print(f"  Claude Code: {os.path.relpath(claude_local, ROOT)} (machine-local, gitignored)")
    if os.path.isdir(os.path.dirname(codex_path)):
        print(f"  Codex:       {os.path.relpath(codex_path, ROOT)}")
    print("  Copilot:     .github/hooks/hooks.json already carries a per-OS `windows` override; no action needed.")
    print("  Read-only guard on /standards/ + /exemplars/ is declarative in .claude/settings.json and always on.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
