# setup-hooks.ps1 — wire Throughline's write-safety hooks for Windows (no Python required).
# PowerShell has built-in JSON, so this needs nothing beyond Windows PowerShell itself.
# Writes the gitignored .claude/settings.local.json (merged) and rebuilds .codex/hooks.json.
# Equivalent to `py tools\setup-hooks.py` on Windows.
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent

function Cmd($ps1) { "powershell -NoProfile -ExecutionPolicy Bypass -File $ps1" }

# Write UTF-8 WITHOUT a BOM. Windows PowerShell 5.1's `Set-Content -Encoding UTF8` prepends a
# BOM, which Node-based JSON parsers (Claude Code, Codex) reject — so write the bytes directly.
function Write-JsonNoBom($path, $text) {
    [System.IO.File]::WriteAllText($path, $text, (New-Object System.Text.UTF8Encoding($false)))
}

# --- Claude Code: merge a hooks block into .claude/settings.local.json ---
$claudeLocal = Join-Path $root ".claude\settings.local.json"
if (Test-Path $claudeLocal) {
    $settings = Get-Content $claudeLocal -Raw | ConvertFrom-Json
} else {
    $settings = [pscustomobject]@{}
}
$claudeHooks = [ordered]@{
    PreToolUse  = @(
        [ordered]@{ matcher = "Write|Edit|MultiEdit|NotebookEdit"; hooks = @([ordered]@{ type = "command"; command = (Cmd ".claude/hooks/validate-immutable-paths.ps1"); timeout = 10 }) },
        [ordered]@{ matcher = "Bash";                              hooks = @([ordered]@{ type = "command"; command = (Cmd ".claude/hooks/validate-bash-safety.ps1");   timeout = 10 }) }
    )
    PostToolUse = @(
        [ordered]@{ matcher = "Write|Edit|MultiEdit"; hooks = @(
            [ordered]@{ type = "command"; command = (Cmd ".claude/hooks/log-tool-use.ps1");      timeout = 15 },
            [ordered]@{ type = "command"; command = (Cmd ".claude/hooks/check-code-quality.ps1"); timeout = 30 }
        ) }
    )
}
$settings | Add-Member -NotePropertyName hooks -NotePropertyValue $claudeHooks -Force
Write-JsonNoBom $claudeLocal ($settings | ConvertTo-Json -Depth 12)

# --- Codex: rebuild .codex/hooks.json for Windows ---
$codexPath = Join-Path $root ".codex\hooks.json"
if (Test-Path (Split-Path $codexPath -Parent)) {
    function CodexCmd($ps1) { "powershell -NoProfile -ExecutionPolicy Bypass -File $ps1" }
    $codex = [ordered]@{
        _comment = "Generated by tools/setup-hooks.ps1 for Windows. Re-run after switching OS. Codex sends the same stdin JSON + exit-2 protocol; the shared .github guard scripts apply."
        hooks    = [ordered]@{
            PreToolUse  = @(
                [ordered]@{ matcher = "apply_patch|Edit|Write"; hooks = @([ordered]@{ type = "command"; command = (CodexCmd ".github/hooks/scripts/validate-immutable-paths.ps1"); timeout = 10; statusMessage = "Guarding /standards/ + /exemplars/ (read-only)" }) },
                [ordered]@{ matcher = "Bash";                   hooks = @([ordered]@{ type = "command"; command = (CodexCmd ".github/hooks/scripts/validate-bash-safety.ps1");   timeout = 10; statusMessage = "Blocking writes to immutable paths + git push/merge (human-only)" }) }
            )
            PostToolUse = @(
                [ordered]@{ matcher = "apply_patch|Edit|Write"; hooks = @(
                    [ordered]@{ type = "command"; command = (CodexCmd ".github/hooks/scripts/log-tool-use.ps1");      timeout = 15; statusMessage = "Appending to wiki/log.md" },
                    [ordered]@{ type = "command"; command = (CodexCmd ".github/hooks/scripts/check-code-quality.ps1"); timeout = 30; statusMessage = "Quality lint on written files" }
                ) }
            )
        }
    }
    Write-JsonNoBom $codexPath ($codex | ConvertTo-Json -Depth 12)
}

Write-Host "Throughline hooks wired for Windows (powershell + .ps1)."
Write-Host "  Claude Code: .claude/settings.local.json (machine-local, gitignored)"
Write-Host "  Codex:       .codex/hooks.json"
Write-Host "  Copilot:     .github/hooks/hooks.json already has a per-OS override; no action needed."
